### PR TITLE
Minorfixes

### PR DESCRIPTION
**Pull request by simonberger**
#1359 Refactoring of phpdoc and deprecated methods

### CODE REVIEW

**Comment by simonberger** [comment]
There is a lot of wrong phpdoc type declaration around the `Frame` base class that should be the decorated class `AbstractFrameDecorator`, `Block`, `Page` or whatever instead.
I would need some time to understand this inheritance structure good enough to try to fix this phpdoc. Surely at many places methods and properties could be many different types.

Do you guys think that work would be worth it or is it ok right now?
IDEs for example aren't able to resolve many methods that are in `AbstractFrameDecorator` while phpdoc notes (directly or indirectly through parent call) Frame right now. Or they report the wrong return type.

**Comment by bsweeney** [comment]
This is all just amazing. Thank you for putting in so much work. I was planning to look at pulling this tonight.

**Comment by bsweeney** [comment]
Everything looks good. If you plan to add more commits please go ahead. Otherwise I'll pull this in.

**Comment by simonberger** [comment]
I plan to go through the rest of the classes and fix all the easy, obvious problems like I did in the other files.
Should be finished today or the weekend. Depends on the time I can find.

Later I maybe try fixing the more complicated problems in context of Frame inheriting and classes.
But that would be done in a separate branch/pull request.
If you have timings regarding a 0.7.1 release I would be fine if you merge that at any time and I also do the rest work mentioned at start of this post in a new pull request.

**Comment by MatthiasKuehneEllerhold** [comment]
You could use the [PHP-CBF](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Fixing-Errors-Automatically) to automate fixing a lot of coding style errors.

**Comment by simonberger** [comment]
Thanks for your note Matthias !
I did not know that tool, but from what I see on the website it doesn't deal with most sort of problems/bugs I found here - beside missing phpdoc for sure.

I'm doing most of the semi manual stuff intentionally though. I walk through all classes and learn much of the DomPDF structure to do more complex stuff later, while one-press fixing the phpdoc of methods it's missing on.
Most other problems I am fixing are just shown by the IDE (missing return value, phpdoc violation, unknown methods...)

Removing some still existing psr style violations at the other hand is a bit annoying. That has been done some time ago I think. But many still or again exist. PhpStorm has a good automatic fix for that. But I do not like the magic. On some code it just does too much and adds more line breaks you would need.

**Comment by MatthiasKuehneEllerhold** [comment]
What I like to do with CBF is I'll let it fix everything and then review everything its done. There are some special cases where it misbehaves and you can easily revert them (via git) but it takes away a lot of pain.

It was just a suggestion to further your cause, not intended as a replacement ;)

**Comment by simonberger** [comment]
I'll definitely try it out.
I like tools helping me to realize crappy mistakes I do. ;)

**Comment by simonberger** [comment]
I finished this task and covered all files.
As described in the associated issue #1359 I plan to do more complicated fixes in a new pull request later.

**Comment by bsweeney** [comment]
I should have mentioned this before. But as you're digging back in don't bother with the html5lib code. Eventually we'll be tossing that for a newer version that's actively maintained.

**Pull request merged**
