### PR TITLE
added namespace for class Cpdf in lib folder

### PR DESCRIPTION
**Pull request by gozeller**
s. issue #1668: https://github.com/dompdf/dompdf/issues/1668

Added a namespace to lib/Cpdf.php to avoid namespace conflicts, e.g. with rospdf/php-pdf 

Not sure, if it's "allowed" to add "\Dompdf" namespace to Cpdf - is it an old/modified version of rospdf/php-pdf?

### CODE REVIEW

**Comment by bsweeney** [comment]
It is a modified version of the original R&OS PDF (back when it was being developed by Wayne Monroe, not the iteration currently hosted on github). I was not involved back when it was introduced with the project so I can't make any statements about its provenance beyond that.

**Comment by shital7mahajan** [comment]
I have added that code from and run following command to check php Combability
Command=> phpcs --standard=PHPCompatibility --extensions=php,module,inc,install,test,profile,theme --runtime-set testVersion 7.2 sites/default/libraries/dompdf

Error: Extension 'cpdf' is removed since PHP 5.1; Use pecl/pdflib instead is still there

any update on it?

**Comment by bsweeney** [comment]
@shital7mahajan you changed the three files indicated and are still receiving the error?

**Comment by shital7mahajan** [comment]
@bsweeney yes.
If we run this command phpcs --standard=PHPCompatibility --extensions=php,module,inc,install,test,profile,theme --runtime-set testVersion 7.2 sites/default/libraries/dompdf
It's showing following error

1] 3444|Warning|Since PHP 7.0, functions inspecting arguments, like debug_print_backtrace(), no longer report the original value as passed to a parameter, but will instead
provide the current value. The parameter "$node" was used, and possibly changed (by reference), on line 3444.
2]198 | ERROR | Extension 'cpdf' is removed since PHP 5.1; Use pecl/pdflib instead
3]480|Warning|Since PHP 7.0, functions inspecting arguments, like debug_backtrace(), no longer report the original value as passed to a parameter, but will instead provide thecurrent value. The parameter "$type" was used, and possibly changed (by reference), on line 480.

So we have resolved that error by https://github.com/dompdf/dompdf/pull/1934
and warning is still there can you please help me to resolved this.

**Pull request merged**
