### PR TITLE
Fix "Permission denied" error when file not found on Windows

### PR DESCRIPTION
**Pull request by godrar**

### CODE REVIEW

**Comment by bsweeney** [comment]
Is this a warning or error? What is `$remoteFile` in your case?

**Comment by godrar** [comment]
Warning: file_put_contents(C:\Users\PRACOW~1\AppData\Local\Temp/ac7f5fff3847d015f6fec14a7c1e75f9): failed to open stream: Permission denied 

$remoteFile: C:\xampp\htdocs\workspace\project1\web\assets\css/../fonts/glyphicons-halflings-regular.ttf 
Font does not exist in folder.

**Comment by bsweeney** [comment]
A warning shouldn't cause problems for rendering the PDF (depending on your PHP/app configuration). But catching for this is a good idea.

**Comment by godrar** [comment]
It would be cool.. File is lock and it can't be unlinked. 
Warning cause problems. Every warning stops my app :)
Thx

**Comment by bsweeney** [comment]
This PR is problematic in that if `$remoteFile` is a URI with protocol and domain (e.g. `http://example.com/somefont.ttf`) the check will fail even if the file exists. I did come up with a tweak, check out commit b5fb3246deccdeda3b0b28e548da255901ed2bb9.

**Pull request closed without merging**
