### PR TITLE
Improve containing block calculations for positioned elements

### PR DESCRIPTION
**Pull request by bsweeney**

### CODE REVIEW

**Comment by Mellthas** [comment]
This looks like a big improvement in general! The following HTML is a test file checking different combinations of position/margin/size. I think the boxes render all as intended now:

<details>
<summary>HTML</summary>

```html
<!DOCTYPE html>
<html>

<head>
<meta charset="UTF-8">
<style>
@page {
    size: 400pt 300pt;
    margin: 50pt;
}

body {
    position: static;
    margin: 10pt;
    padding: 10pt;
    outline: 0.5pt solid black;
}

div {
    position: absolute;
    width: 98pt;
    height: 98pt;
    border: 1pt solid red;
}

.zero {
    top: 0;
    left: 0;
    right: auto;
    bottom: auto;
    margin: auto;
}

.static {
    top: auto;
    left: auto;
    right: auto;
    bottom: auto;
    margin: auto;
}

.center {
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    margin: auto;
}

.percentage {
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    width: 65%;
    height: 65%;
    margin: auto;
}
</style>
</head>

<body>

<div class="zero">Zero position</div>
<div class="static">Auto position</div>
<div class="center">Auto margins</div>
<div class="percentage">Percentage size</div>

</body>

</html>
```

</details>

Output: [position-absolute.pdf](https://github.com/dompdf/dompdf/files/7307350/position-absolute.pdf)

**Comment by bsweeney** [comment]
> This looks like a big improvement in general! The following HTML is a test file checking different combinations of position/margin/size. I think the boxes render all as intended now

Thanks! It's definitely a bit rough around the edges since I didn't quite have the focus I needed. I was actually going to push the changes off for another release because of some challenges, but a lot of the work you did recently made addressing this issue possible.

Your comments are spot on, I'll have some updates soon.

**Comment by Mellthas** [comment]
In the interest of moving this forward for the next release, I have pushed the branch [block-formatting-context-suggestions](https://github.com/dompdf/dompdf/tree/block-formatting-context-suggestions), with a few suggested changes on top of this:

* I have filled out the rules for determining width and height based on your work.
* Following that, I think we can remove most code from the absolute and fixed `Positioner` classes, and just let them apply `top` and `left`. This makes the positioning consistent between absolute and fixed and especially solves the confusing difference in `bottom` handling for fixed (basing the position off the top edge of the element instead of off the bottom edge).

For the remaining issues, I will comment inline.

**Comment by bsweeney** [comment]
Thanks for the work. I think these changes all look good. I'll review and pull them in so we can finish this one out.

**Comment by bkurihara** [comment]
could you guys tell me when this new version will be released?

**Pull request closed without merging**
