### PR TITLE
Prevent case exception in text renderer

### PR DESCRIPTION
**Pull request by mudasser1985**
On line 158 of this file width is adding up that expects a number.
In case of " auto " width, it throws an error as following and breaks the PDF render.
"ErrorException: A non-numeric value encountered in /Path_To_Project/vendor/dompdf/dompdf/src/Renderer/Text.php:158"

suggestion: type casting the $width to float will convert the string into a numeric value that will prevent the ErrorException.

### CODE REVIEW

**Comment by bsweeney** [comment]
In the future please submit any pull requests against the develop branch.

Do you have a sample document that causes the issue?

**Comment by mudasser1985** [comment]
> In the future please submit any pull requests against the develop branch.
> 
> Do you have a sample document that causes the issue?

Please find the attached zip file for the sample document that is causing the issue. Also the screenshot of actual error is attached for your reference. 

looking forward to your response for this error follow up.  

Non-Numeric-Value-Error-Screenshot
[BA.zip](https://github.com/dompdf/dompdf/files/6230458/BA.zip)

**Comment by mudasser1985** [comment]
Hello bsweeney,
when can i expect this issue to be fixed in master branch?

**Comment by bsweeney** [comment]
I apologize, but I've not been able to find time to work on the next release up to now. I'm still unable to reproduce the issue with your sample. It could be a combination of factors (HTML + CSS as well as page size, DPI, etc). I'll do a bit more investigation but don't see any harm including this change.

**Comment by fd6130** [comment]
> I apologize, but I've not been able to find time to work on the next release up to now. I'm still unable to reproduce the issue with your sample. It could be a combination of factors (HTML + CSS as well as page size, DPI, etc). I'll do a bit more investigation but don't see any harm including this change.

Have you try with the `declare(strict_types=1);` after the `<?php` ? Only that will avoid auto convert in php and the error might occurs, i guess?

**Comment by Mellthas** [comment]
This is probably related to #2347.

**Comment by Mellthas** [comment]
While the proposed fix does work, I think the proper fix is to ensure that the width is resolved at this point. Does the error still occur with the current `develop` state, i.e. with 51c21a763aa9dd37eb910f409f05b6072074899c in? I cannot reproduce the error, neither with the sample provided here, nor with the one from #2347, even using version 1.0.2.

**Comment by bsweeney** [comment]
responded on 2347 ... seems to be caused by a specific structure of invalid html

**Comment by Mellthas** [comment]
Have managed to reproduce it now. Regarding the discussion in #2347, I think it might still be worthwhile to take this, because the source problem seems harder to track down.

**Pull request merged**
