### PR TITLE
fix issue #1110

### PR DESCRIPTION
**Pull request by kirugan**

### CODE REVIEW

**Comment by bsweeney** [comment]
I'll probably not commit this to the 0.6.x code base since 0.7.0 is about to be released.

**Comment by kirugan** [comment]
@bsweeney, when 0.7 stable will be released ?

**Comment by bsweeney** [comment]
All I really need to do is click a button. Unless something major comes up the current master branch will be the stable 0.7.0 release. I just need to go over the documentation and run through some local rendering tests to make sure everything is good to go. But I don't have a definitive timeline ... maybe in the next week?

**Comment by kirugan** [comment]
It seems like the same bug appears in v0.7.0-beta3. So what should I do? Create new bug and close this one or commit fix with link to this issue?

**Comment by bsweeney** [comment]
Probably best to close this and create a new PR against master.

**Comment by kirugan** [comment]
Ok, I`ve created #1125 PR against master.

**Pull request closed without merging**
