### PR TITLE
Fixed some PHP7.1 string arithmetic issues, update to PHPUnit 4.8, fixed test

### PR DESCRIPTION
**Pull request by tomlankhorst**
String arithmetic works slightly different in PHP7.1. I've added some explicit typecasting on places to make dompdf compatible with PHP 7.1

Example:
https://3v4l.org/9h376

 I've also changed PHPUnit version to recent 4.8
Fixed a detail in the `testRender()` test: no `$dompdf->output()` or` ->stream()` was called so the output buffer opened by `->render()` was not closed.

### CODE REVIEW

**Comment by sisve** [comment]
This PR solves many of my issues, except some arithmetics in Block.php

https://github.com/tomlankhorst/dompdf/blob/2eaf8fe0f1c95ab76e7a428a39a54dd240e2b2ec/src/Renderer/Block.php#L139-L167

```A non-numeric value encountered

~/vendor/dompdf/dompdf/src/Renderer/Block.php:148
~/vendor/dompdf/dompdf/src/Renderer/Block.php:68
~/vendor/dompdf/dompdf/src/Renderer.php:293
~/vendor/dompdf/dompdf/src/Renderer.php:101
~/vendor/dompdf/dompdf/src/Renderer.php:194
~/vendor/dompdf/dompdf/src/FrameReflower/Page.php:140
~/vendor/dompdf/dompdf/src/FrameDecorator/AbstractFrameDecorator.php:828
~/vendor/dompdf/dompdf/src/Dompdf.php:835
```

$border_box:
```
array (
  0 => 34.01574803149606,
  1 => 34.01574803149606,
  2 => 543.9685039370079,
  3 => 'auto',
)
```

**Comment by necenzurat** [comment]
any updates on the merge, i am stuck without this.

**Comment by bsweeney** [comment]
It's in the queue. Not sure it'll happen this week or next, but soon.

**Comment by necenzurat** [comment]
oh well, it's time to spend 2 hours downgrading vagrant homestead to 5.6.x. #fml

**Comment by bsweeney** [comment]
Sorry we can't get it out sooner. Why not 7.0?

**Comment by necenzurat** [comment]
Laravel's vagrant box (homestead) comes with 7.1, and I just want to code
redo the vm
​ config​

On Jan 6, 2017 1:26 AM, "Brian Sweeney" <notifications@github.com> wrote:

Sorry we can't get it out sooner. Why not 7.0?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/dompdf/dompdf/pull/1339#issuecomment-270788173>, or mute
the thread

**Comment by bsweeney** [comment]
@necenzurat if you have time can you check to see if there's any improvement with the latest code in the develop branch?

**Comment by necenzurat** [comment]
Will try, can't promise anything, i am in hell week

**Pull request merged**
