### PR TITLE
Fix deprecated function usage.

### PR DESCRIPTION
**Pull request by rsanzante**
This commit tries to fix https://github.com/dompdf/dompdf/issues/2007.

See comments because I'm don't know if this is ok.

### CODE REVIEW

**Comment by noone-silent** [comment]
This looks good for me. The get_value "ascender" and "descender" is only supported for PDFLib 6, from PDFLib 7 on you already should use info_font

**Comment by rsanzante** [comment]
It seems fails are not due the commit, but a CI configuration issue. 
They fail in the first 20 seconds with this kind of error: 
image

The interesting point is here:
```The command "phpenv global 5.5" failed and exited with 1 during.```

The other fails because of 5.4:
```The command "phpenv global 5.4" failed and exited with 1 during .```

**Comment by bsweeney** [comment]
Yes, CI is borked right now. If nobody submits a PR I'll see about fixing it.

This also looks correct to me based on the [PDFLib 9 API reference](https://www.pdflib.com/fileadmin/pdflib/pdf/manuals/PDFlib-9.0.3-API-reference.pdf).

**Comment by rsanzante** [comment]
Thanks for your comments @bsweeney. I've updated the PR according.

**Pull request merged**
