### PR TITLE
Adding coding standard based on PSR2 and phpcs

### PR DESCRIPTION
**Pull request by lsolesen**
I've tested the library with PHPCS. I've added the actual ruleset used for the rest of the coding standard in phpcs.xml. That makes i possible to standardize contributions. Then it is possible to fix one coding standard violation at a time according to PSR2 standards.

### CODE REVIEW

**Comment by lsolesen** [comment]
I changed the pull request to reflect the actual coding standards used right now without anything being changed. 

    

That line in `phpcs.xml` indicates which rules can be fixed automatically by phpcbf-tool bundled with phpcs. However, it will be quicker to review without having all the automatic stuff done in the same commit.

**Comment by bsweeney** [comment]
Thanks for the update. Were the other changes you had previously committed just the automated fixes?

**Comment by lsolesen** [comment]
Yes. That was the automated fixes. I will help fix the manual one also if
you accept the pull request.

Den man. 2. maj 2016 02.44 skrev Brian Sweeney <notifications@github.com>:

**Comment by lsolesen** [comment]
Do you want me to do more with this one right now?

Den man. 2. maj 2016 07.07 skrev Lars Olesen <lars@intraface.dk>:

**Comment by bsweeney** [comment]
Feel free to work on it more. I'm not opposed to you pushing more commits our way related to these changes. I'm trying to make sure the master is in good shape for the 0.7.0 release. I'll probably pull this in to develop after that.

**Pull request closed without merging**
