### PR TITLE
Fixed issues with list bullets on page break

### PR DESCRIPTION
**Pull request by naitsirch**
There are several issues mentioning problems with the rendering of bullets when the page is breaked within a list (see #403, #872 and #1045).

When dompdf detects that the content of a list item overflows the page, it clones the item to the next page and moves all following content to it. If the first child of the item leads to the overflow, the bullet is still drawn at the end of the first page and no bullet is drawn for the cloned item on the next page.

In fact there are three issues that I address in this PR:
* The origin list item gets removed if it has no content anymore after it was splitted.
* The cloned element is marked as non-splitted if the origin item was removed, so that the bullet of the cloned item on the next page gets rendered.
* Copy the value of the attribute `dompdf-counter` of the origin bullet element. Because the attribute of the new bullet element that is created for the cloned list item was not filled correctly, so that the bullet was not rendered if an ordered list (`<ol>`) is used.

The fix is a bit hacky, but I couldn't find a cleaner way of fixing the issue. The problem is that the bullet is handled by a custom DOM element which makes some checks more complicated.

Maybe this could be changed sometime.

I hope this PR could be merged, soon. If so please create a new release, so that it gets installed when composer is used.

### CODE REVIEW

**Comment by bsweeney** [comment]
@naitsirch do you have some sample HTML that shows the issue? I attempted to reproduce but didn't have any luck.

I thought we had addressed some of these issues through various updates. And if so the relevant issues should be closed.

**Comment by naitsirch** [comment]
Yes, it is a bit tricky. It only happens if there are child items within the list item, that is wrapped to the next page.
Here's the code to reproduce:
```php
<?php
require 'vendor/autoload.php';

use Dompdf\Dompdf;

$html = <<<HTML
<!DOCTYPE html>
<html>
    <head>
        <style>
            li { font-size: 15pt; font-family: Helvetica, sans-serif; }
            p { margin: 0; padding: 0; }
            #last { color: red; line-height: 1.35; }
        </style>
    </head>
    <body>
        <ul>
            <li>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</li>
            <li>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</li>
            <li>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</li>
            <li>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</li>
            <li>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</li>
            <li>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</li>
            <li>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</li>
            <li>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</li>
            <li>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</li>
            <li>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</li>
            <li>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</li>
            <li>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</li>
            <li>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</li>
            <li>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</li>
            <li>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</li>
            <li id="last">Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</li>
            <li>
                <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</p>
                <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</p>
            </li>
            <li>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</li>
        </ul>
    </body>
</html>
HTML;

$dompdf = new Dompdf();
$dompdf->loadHtml($html);
$dompdf->setPaper('A5', 'landscape');
$dompdf->render();
$dompdf->stream();
```
And this is a screenshot that shows the problem:
screenshot_20181114_211041

I hope this helps.

**Comment by naitsirch** [comment]
I have tested it with master branch now, too. The issue still exists.

**Comment by bsweeney** [comment]
I was testing with the develop branch and wasn't able to reproduce with your sample. Switching to master I was. I'm going to set aside the PR until I have a chance to review it a bit more since we need to get the next release out.

**Comment by naitsirch** [comment]
Can you attach a screenshot how it looks on your side?

**Comment by bsweeney** [comment]
Things are a tad better now but there are still issues after the page break. And the issue with not flowing over the bullet for overly large LI content is still a problem (per issue 403).

So, we will be looking at this a bit more.

**Comment by bsweeney** [comment]
OK, nvm. I was looking at the input incorrectly. I think we render OK now. I am curious to see if there is any affect on this after apply the widow support from #1356.

**Comment by bsweeney** [comment]
I think this is no longer needed with the current. I'm going to go ahead and close for now. If the issue comes back up I'll revisit the commit at that time.

**Pull request closed without merging**
