### PR TITLE
Fix PHP7.4 bug

### PR DESCRIPTION
**Pull request by neoteknic**
Maybe relase a 0.9.0 version (with : remove php5 support + fix 7.4)

### CODE REVIEW

**Comment by neoteknic** [comment]
+ useless travis error, remove php 5 obsolete unsupported version...

**Comment by troosan** [comment]
@neoteknic or you can specify in .travis.yml that 5.x should run on trusty.
```
matrix:
    include:
        - php: 5.4
          dist: trusty
        - php: 5.5
          dist: trusty
    exclude:
        - php: 5.3
        - php: 5.4
```

**Comment by kosmonowt** [comment]
👍 works for us. needed to be merged urgently due to needs in production. 🙏

**Comment by bsweeney** [comment]
Will merge #2029, develop is merged into master for the release, which makes this PR unnecessary.

**Comment by jbenavidesv87** [comment]
So... Is this already up? Today I just had this problem and had to change the code directly on file.

**Comment by bsweeney** [comment]
@jbenavidesv87 should be in the most recent release. What version of Dompdf are you using?

**Comment by jbenavidesv87** [comment]
I have updated in locally but no in production, haha. Thank you!

**Comment by bsweeney** [comment]
I do it all the time ha ha

**Pull request closed without merging**
