### PR TITLE
Fix layout_line add_line

### PR DESCRIPTION
**Pull request by simonberger**
Addresses:
#2124 
#1315

### CODE REVIEW

**Comment by simonberger** [comment]
This has a little BC if _layout_line is not considered as an internal method.

**Comment by sakihl** [comment]
Hi @simonberger. So far I have just been using this fix locally on a PC but I need it for a project going live in September. Before creating my own branch and setting up my project's composer to pull from there I just thought I would ask the question first. Do you know what the approximate timescale for 0.8.6 release might be?

**Comment by bsweeney** [comment]
We have a few issues left to address in the current code Base for 0.8.6. Trying to push through that so we can get the release out since there are some issues introduced in 0.8.5 that are addressed in this release.

I would expect it before September, but I can’t give a hard deadline just yet.

**Comment by sakihl** [comment]
Thank you for your quick and helpful response.

**Pull request merged**
