### PR TITLE
Update README.md: Adding "Framework Integration"

### PR DESCRIPTION
**Pull request by ThomasLandauer**
The idea would be to collect all bundles for all frameworks...

### CODE REVIEW

**Comment by bsweeney** [comment]
[There is a wiki page for that](https://github.com/dompdf/dompdf/wiki/Third-party-Integrations).

**Comment by ThomasLandauer** [comment]
OK, but since it's that short, I'd rather add those two on README too. Why? To me, it's an installation question: The earlier I know what I have to actually install, the better.

**Comment by bsweeney** [comment]
I have no problem with that. Would you mind adding existing noted integrations from the wiki, plus the laravel package?

**Comment by ThomasLandauer** [comment]
Sure. I also deleted the wiki page.

**Comment by bsweeney** [comment]
If that list were to expand too much, we may want to restore the wiki page and list the most popular on the readme with a link. But the list is small so that's fine.

**Pull request merged**
