### PR TITLE
PHP 8.4 compat

### PR DESCRIPTION
**Pull request by swiffer**
- https://php.watch/versions/8.4/implicitly-marking-parameter-type-nullable-deprecated

### CODE REVIEW

**Comment by swiffer** [comment]
supersedes #3508

**Comment by swiffer** [comment]
ok, should PHP 7.1 support be restored or is it going to be deprecated considering it's EOL since 2018?

**Comment by swiffer** [comment]
ok, done - thanks for the detailed reply!

**Comment by bsweeney** [comment]
Nicely done thanks for working on this.

**Comment by oleibman** [comment]
Thank you for this. Do you have plans to make a release which includes this PR any time soon?

**Comment by bsweeney** [comment]
Yes, looking to release a new version soon.

**Comment by wblessen** [comment]
> Yes, looking to release a new version soon.

Is it possible to integreate this:

https://github.com/dompdf/dompdf/pull/3269

Can I help with something?

**Comment by bsweeney** [comment]
@wblessen not with the PHP compatibility update, which I am going to push through this week. But I will look to try and finish up that for release soon as well. Feel free to review the changes and make suggestions if you are able.

**Comment by wblessen** [comment]
Thank you for all your work!

I will try to move the changes in a pull request with the current source this week

**Pull request merged**
