### PR TITLE
Fixing issue #1423: support concurrent loading of the same font in FontMetrics::registerFont()

### PR DESCRIPTION
**Pull request by marrch-caat**
Small patch that prevents collisions when several processes place a font to the same temporary file and then one of them deletes it.
Also some minor code optimization made to the only affected function.

### CODE REVIEW

**Comment by bsweeney** [comment]
We could probably save some trouble by using `tempnam` instead of the MD5 hash of the remote file when creating the temporary file name. You wouldn't need the `do...while` loop in that case.

Then the main thing we'd want need to try to avoid is writing to the stored font file while another process generating the PDF document. I don't know how much extra logic we want to put in to handle this case.

**Comment by marrch-caat** [comment]
Oh, I didn't think about it. @bsweeney should I do another pull-request with tempnam? Of course using it would be much simpler...

**Comment by bsweeney** [comment]
No worries. I think I just about have it all done. Took a bit longer because of the changes I made that broke your PR.

**Comment by bsweeney** [comment]
I dunno what I did with that last pull request, but your changes are now merged. Sorry you don't show up in the commit history, I prefer to show where things came from.

**Pull request closed without merging**
