### PR TITLE
Combine autoloader?

### PR DESCRIPTION
**Pull request by barryvdh**
Not sure if this makes sense, but when you have to require 3 loaders, why not combine them together in 1 file? If you need to change/add something later on, people don't have to change anything..

Also moved it out of the /src folder, which might be confusing together with #958

### CODE REVIEW

**Comment by vkeranov** [comment]
+1

**Comment by bsweeney** [comment]
Oh, github. Why can't I lazy merge?!? Wanna rebase this one again?

**Comment by bsweeney** [comment]
alright, alright ... I took care of it (it was a simple merge anyway)

**Comment by barryvdh** [comment]
Sorry, I forgot :(

**Comment by bsweeney** [comment]
No worries, it was an easy merge. I was just being lazy.

**Pull request merged**
