### PR TITLE
Added soft hyphen support (addresses #104)

### PR DESCRIPTION
**Pull request by naitsirch**
This PR adds support for soft hyphen for correct line breaking and hiding the hyphen if there is no break.

Imagine these lines of code:
```php
$html = "<div style=\"width: 40mm; background-color: red;\">Anti&shy;disestablish&shy;mentarianism</div>";

$dompdf = new \Dompdf\Dompdf();
$dompdf->loadHtml($html);
$dompdf->setPaper('A4', 'landscape');
$dompdf->render();

echo $dompdf->output();
```

Without this PR the result would look like:
grafik

With this PR applied it would look like:
grafik

I would be happy if this change could be applied soon. If there are any issues with this PR just let me know :-)

### CODE REVIEW

**Comment by naitsirch** [comment]
In tables where the width should force a break in the word, it does not work completely. But at least the hyphens get removed.

grafik

**Comment by naitsirch** [comment]
@bsweeney You have changed the regex that splits the text into words to this:
```php
// split the text into words
// The regex splits on everything that's a separator (^\S double negative), excluding nbsp (\xa0), plus dashes
// This currently excludes the "narrow nbsp" character
$words = preg_split('/([^\S\xA0]+|-+)/u', $text, -1, PREG_SPLIT_DELIM_CAPTURE);
```

As I have modified the regex in this PR, would this be the correct update?
```php
$words = preg_split('/([^\S\xA0]+|[\-\xC2\xAD]+)/u', $text, -1, PREG_SPLIT_DELIM_CAPTURE);
```

**Comment by bsweeney** [comment]
On initial look I believe that's should work. I haven't fully reviewed the PR yet so if I find any issues I'll let you know.

**Comment by naitsirch** [comment]
I have rebased the PR on develop branch.

**Comment by GenieTim** [comment]
What is the state of this PR? I would be highly interested in working hyphenation.

**Comment by bsweeney** [comment]
FYI, this will only add soft hyphen support not general hyphenation. I'll take a look at this for the next release since the logic is straightforward though I will probably push one more release out if I find any issues..

**Comment by GenieTim** [comment]
Perfect, thank you very much!

**Comment by naitsirch** [comment]
@bsweeney I have rebased the PR on develop branch once again ;-)

**Comment by naitsirch** [comment]
Happy to See this merged :-) thank you

**Pull request merged**
