### PR TITLE
Updates for compatibility with PHP 8

### PR DESCRIPTION
**Pull request by bsweeney**

### CODE REVIEW

**Comment by vladislavtkachenko** [comment]
Hi! Any news? 
I tested this branch on my pdf, no errors occurred.
Thank you

**Comment by sandervanhooft** [comment]
@vladislavtkachenko Dompdf is still throwing errors on php8 ([test results](https://github.com/laravel/cashier-mollie/pull/276/checks?check_run_id=1524696604)).

**Comment by unfulvio** [comment]
branch works on my end so far, no PHP 8 errors in the project I'm working with - thanks!

**Comment by dyaskur** [comment]
latest released version(0.8.6) also work fine on php 8 in my projects. I just install using php 7.4 and run using php 8. hope release version that support php 8 install. I can not using php8-compat branch because conflict with laravel-dompdf

**Comment by corsair** [comment]
Can also confirm this works, but can't utilize it for the same reason as @dyaskur.

**Comment by vladislavtkachenko** [comment]
I use laravel-dompdf and I don't have any problems

**Comment by dyaskur** [comment]
@vladislavtkachenko How do you install it? when I change domdf to `"dompdf/dompdf": "dev-php8-compat"` return below error:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - barryvdh/laravel-dompdf dev-master requires dompdf/dompdf ^0.8.6 -> found dompdf/dompdf[v0.8.6] but it conflicts with your root composer.json require (dev-php8-compat).
    - barryvdh/laravel-dompdf v0.8.7 requires dompdf/dompdf ^0.8 -> found dompdf/dompdf[v0.8.0, ..., v0.8.6] but it conflicts with your root composer.json require (dev-php8-compat).
    - barryvdh/laravel-dompdf 0.8.x-dev is an alias of barryvdh/laravel-dompdf dev-master and thus requires it to be installed too.
    - Root composer.json requires barryvdh/laravel-dompdf ^0.8.7 -> satisfiable by barryvdh/laravel-dompdf[v0.8.7, 0.8.x-dev (alias of dev-master)].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
```

**Comment by vladislavtkachenko** [comment]
@dyaskur I use the fork of this repository, because I need Cyrillic support, so I installed the '0.8.6.3' tag for testing. If you want, you can also use my fork, it is based on the php8-compat branch, but the Cyrillic alphabet is added

`
     {
            "type": "vcs",
            "url": "https://github.com/vladislavtkachenko/dompdf.git",
            "canonical": false
        },
`

**Comment by hmawla** [comment]
> I use laravel-dompdf and I don't have any problems

Do you mean that you are using laravel-dompdf with php8 with no problems? cuz it doesn't seem to work for me. So if you can enlighten me, please XD

**Comment by dyaskur** [comment]
> > I use laravel-dompdf and I don't have any problems
> 
> Do you mean that you are using laravel-dompdf with php8 with no problems? cuz it doesn't seem to work for me. So if you can enlighten me, please XD

he already gives the clue, just edit composer.lock. But I conform with my current state, just install on php 7.4 then run on php 8.

**Comment by itajackass** [comment]
> 
> 
> @vladislavtkachenko How do you install it? when I change domdf to `"dompdf/dompdf": "dev-php8-compat"` return below error:
> 
> ```
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - barryvdh/laravel-dompdf dev-master requires dompdf/dompdf ^0.8.6 -> found dompdf/dompdf[v0.8.6] but it conflicts with your root composer.json require (dev-php8-compat).
>     - barryvdh/laravel-dompdf v0.8.7 requires dompdf/dompdf ^0.8 -> found dompdf/dompdf[v0.8.0, ..., v0.8.6] but it conflicts with your root composer.json require (dev-php8-compat).
>     - barryvdh/laravel-dompdf 0.8.x-dev is an alias of barryvdh/laravel-dompdf dev-master and thus requires it to be installed too.
>     - Root composer.json requires barryvdh/laravel-dompdf ^0.8.7 -> satisfiable by barryvdh/laravel-dompdf[v0.8.7, 0.8.x-dev (alias of dev-master)].
> 
> Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
> ```

Hi i'm in the same case. How can I 

> 
> 
> @vladislavtkachenko How do you install it? when I change domdf to `"dompdf/dompdf": "dev-php8-compat"` return below error:
> 
> ```
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - barryvdh/laravel-dompdf dev-master requires dompdf/dompdf ^0.8.6 -> found dompdf/dompdf[v0.8.6] but it conflicts with your root composer.json require (dev-php8-compat).
>     - barryvdh/laravel-dompdf v0.8.7 requires dompdf/dompdf ^0.8 -> found dompdf/dompdf[v0.8.0, ..., v0.8.6] but it conflicts with your root composer.json require (dev-php8-compat).
>     - barryvdh/laravel-dompdf 0.8.x-dev is an alias of barryvdh/laravel-dompdf dev-master and thus requires it to be installed too.
>     - Root composer.json requires barryvdh/laravel-dompdf ^0.8.7 -> satisfiable by barryvdh/laravel-dompdf[v0.8.7, 0.8.x-dev (alias of dev-master)].
> 
> Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
> ```

Have you solved? I'm in the same situation. I don't know how to retrieve correct version with composer, for php8

**Comment by vladislavtkachenko** [comment]
> > @vladislavtkachenko How do you install it? when I change domdf to `"dompdf/dompdf": "dev-php8-compat"` return below error:
> > ```
> > Your requirements could not be resolved to an installable set of packages.
> > 
> >   Problem 1
> >     - barryvdh/laravel-dompdf dev-master requires dompdf/dompdf ^0.8.6 -> found dompdf/dompdf[v0.8.6] but it conflicts with your root composer.json require (dev-php8-compat).
> >     - barryvdh/laravel-dompdf v0.8.7 requires dompdf/dompdf ^0.8 -> found dompdf/dompdf[v0.8.0, ..., v0.8.6] but it conflicts with your root composer.json require (dev-php8-compat).
> >     - barryvdh/laravel-dompdf 0.8.x-dev is an alias of barryvdh/laravel-dompdf dev-master and thus requires it to be installed too.
> >     - Root composer.json requires barryvdh/laravel-dompdf ^0.8.7 -> satisfiable by barryvdh/laravel-dompdf[v0.8.7, 0.8.x-dev (alias of dev-master)].
> > 
> > Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
> > ```
> 
> Have you solved? I'm in the same situation. I don't know how to retrieve correct version with composer, for php8

try to use "barryvdh/laravel-dompdf"  ^0.9.0

**Comment by ermalkonjufca1** [comment]
> @dyaskur I use the fork of this repository because I need Cyrillic support, so I installed the '0.8.6.3' tag for testing. If you want, you can also use my fork, it is based on the php8-compat branch, but the Cyrillic alphabet is added
> 
> `"dompdf/dompdf": "0.8.6.3"`
> `{ "type": "vcs", "url": "https://github.com/vladislavtkachenko/dompdf.git", "canonical": false },`

many hours looking for a solution, now I found it, thanks a lot @vladislavtkachenko,

**Pull request merged**
