### PR TITLE
Improved PHPdoc of stream()

### PR DESCRIPTION
**Pull request by ThomasLandauer**
Is there a specific reason why you're not setting the 'Content-Type:' header to 'application/pdf'? Can I add this here?

### CODE REVIEW

**Comment by bsweeney** [comment]
The content-type header is set by either a) the adapter (in the case of PDFLib and GD) or b) the PDF generating back-end (in the case of CPDF).

**Comment by ThomasLandauer** [comment]
Yeah, thanks, you're right!
Details: When calling `$dompdf->stream('dom.pdf');` I get the correct Content-Type. However, when "wrapping" it into a Symfony Response object like this
`return new Response ($dompdf->stream('dom.pdf'));`
... then Symfony sends Content-Type `text/html`

**Comment by bsweeney** [comment]
Ah, now that's interesting. It's possible that Symfony is buffering the output and setting it's own content type header. You might also have to set the content type manually if it sets a default of "text/html".

Actually, you may want to use the `output()` method and rely on Symfony to handle the response to the client.

```
return new Response(
    $dompdf->output(),
    Response::HTTP_OK,
    array('content-type' => 'application/pdf')
);
```

You would have to set the headers yourself that are typically set by dompdf. The Symfony documentation may be useful here: http://symfony.com/doc/current/components/http_foundation/introduction.html#serving-files.

**Comment by ThomasLandauer** [comment]
Thanks for the link - that's just perfect! :-)

BTW: Please merge the pull request.

**Pull request closed without merging**
