### PR TITLE
do not try to apply alpha mask if no alpha channel is present

### PR DESCRIPTION
**Pull request by digibeuk**
this is a new pull request duplicate of https://github.com/dompdf/dompdf/pull/906#issuecomment-117785281 to merge changes to develop

### CODE REVIEW

**Comment by bsweeney** [comment]
Not quite what I meant. It's a pain to merge code from master because of the significant changes we've made. Possible, but not pleasant with conflicting commits. Unless you don't mind me just reproducing your changes ... but I do like to give credit in the commit history. Could you check out develop, make the changes, and submit a new PR?

**Comment by digibeuk** [comment]
i think it is better you use my changes, I know for sure my change work because we use it in production on a high traffic platform. Making the changes on develop means i am doing it on code I can test not so easily

**Comment by bsweeney** [comment]
We'll take a closer look then. Since the change is confined to a small bit of code I don't expect any issues merging with the develop branch so long as no other changes have been made to that section of code.

**Comment by bsweeney** [comment]
Possibly relevant to #866?

**Comment by SharkWipf** [comment]
I just tested this code, it seems to solve the mystery Imagick broken image issues (including but not limited to #432 and #920, possibly most transparency-related issues).  
Probably worth looking into merging this.

**Comment by bsweeney** [comment]
@SharkWipf thanks for the follow up. I'll try to pull this change in for the next release.

**Pull request merged**
