### PR TITLE
Create packaged release with composer

### LINKED ISSUE #2608: Use composer to create packaged release ?
Today DomPdf can either use composer's autoload mechanism, or use its custom autoload mechanism. I would like to suggest to drop the custom autoload mechanism. First of all because nowadays composer is quite ubiquitous.

But more importantly, because of the fact that DomPdf has this custom mechanic, it makes it mandatory for all (transitives) dependencies to also have such thing. This is visible in packaged version of DomPdf's `autoload.inc.php`:

```php
// Sabberworm
spl_autoload_register(function($class)
{
    if (strpos($class, 'Sabberworm') !== false) {
        $file = str_replace('\\', DIRECTORY_SEPARATOR, $class);
        $file = realpath(__DIR__ . '/lib/php-css-parser/lib/' . (empty($file) ? '' : DIRECTORY_SEPARATOR) . $file . '.php');
        if (file_exists($file)) {
            require_once $file;
            return true;
        }
    }
    return false;
});

// php-font-lib
require_once __DIR__ . '/lib/php-font-lib/src/FontLib/Autoloader.php';

//php-svg-lib
require_once __DIR__ . '/lib/php-svg-lib/src/autoload.php';
```

Removing entirely `src/autoload.php` and similar in dependencies would simplify maintenance (in at least 3 packages) and allow dependencies to manage their own dependencies independently of DomPdf.

As for the packaged version, if is deemed too important to drop it, then it can be re-created with automated third party tools, such as https://php-download.com/package/dompdf/dompdf. Even though my personal preference would be to not recommend pre-packaged version, because composer really is superior to "download and unzip".

I'd create a PR for that. What do you think ?

### PR DESCRIPTION
**Pull request by PowerKiKi**
This entirely replace our custom autoload mechanism. The added benefit
is reduced maintenance for DomPDF itself but also its dependencies. And
it opens up the possibility to add new dependency transparently, without
the need to manage their autoloading.

Fixes #2608
Closes #2779
Fixes https://github.com/dompdf/utils/issues/12
Closes https://github.com/dompdf/utils/pull/13

### CODE REVIEW

**Comment by PowerKiKi** [comment]
`zipinfo -1 build/dompdf-1.2.0.zip` would give something similar to the following. The critical part being that `dompdf/autoload.inc.php` is 100% compatible across packages.


# Before

```
dompdf/CONTRIBUTING.md
dompdf/LICENSE.LGPL
dompdf/README.md
dompdf/SECURITY.md
dompdf/VERSION
dompdf/autoload.inc.php
dompdf/composer.json
dompdf/lib/*  all files redacted for brevity
dompdf/phpcs.xml
dompdf/src/*  all files redacted for brevity
```

# After

```
dompdf/CONTRIBUTING.md
dompdf/LICENSE.LGPL
dompdf/README.md
dompdf/SECURITY.md
dompdf/VERSION
dompdf/autoload.inc.php
dompdf/vendor/*  all files redacted for brevity
```

**Review by bsweeney — COMMENTED** [review]
Do you have the time/inclination to make this a bit more OS-agnostic? `rm` and `cp` have equivalent PHP functions, but `which` does not. Maybe first check for a `COMPOSER` environment variable for identifying the location?

**Comment by bsweeney** [comment]
I do currently use windows as my primary development environment. But I understand not wanting to build out complexity. I do have access to linux and mac so I can run the script there.

**Comment by Mellthas** [comment]
Using something like Git Bash or WSL on Windows might also be an option.

**Pull request merged**
