### PR TITLE
Additional fixes for PHP 8.1 deprecations

### PR DESCRIPTION
**Pull request by Mellthas**
Following #2659. See the individual commits, which also include some small related cleanups.

### CODE REVIEW

**Comment by bsweeney** [comment]
Added two more changes. I'm working on an update to php-font-lib to address issues there as well. We should update the php-font-lib version referenced once a new release is available.

php-svg-lib looks to be compatible at a base level, at least that's how it appears after some limited testing. However, the php-css-parser dependency does not yet have a release fully compatible with PHP 8.1.

**Comment by bsweeney** [comment]
I think this is ready to merge.

**Comment by Mellthas** [comment]
Since php-svg-lib requires PHP 7.4 now, won’t raising the php-svg-lib dependency implicitly raise the requirement for dompdf, too? So maybe the requirement should be `^0.3.3 || ^0.4.0`.

**Comment by Mellthas** [comment]
I still get a deprecation warning in php-font-lib when using any font other than the standard PDF ones (e.g. DejaVu):

`Deprecated: mb_strlen(): Passing null to parameter #1 ($string) of type string is deprecated in .../dompdf/vendor/phenx/php-font-lib/src/FontLib/Glyph/Outline.php on line 99`

**Comment by bsweeney** [comment]
> So maybe the requirement should be `^0.3.3 || ^0.4.0`

Of course you are correct. Re-pushed.

> I still get a deprecation warning in php-font-lib

How did I miss that? 😞

**Comment by bsweeney** [comment]
That was _very_ sloppy of me. I had an uncommitted change in my local that I _totally_ missed.

**Comment by bsweeney** [comment]
Well _that_ was embarrassing! Thanks for spotting my mistakes there and for helping get php-font-lib back in order, @Mellthas. How are we looking now?

**Comment by Mellthas** [comment]
I think we are good now, haven’t found any further issues!

**Review by bsweeney — APPROVED** [review]

**Pull request merged**
