### PR TITLE
use JSON for font metrics cache instead of PHP

### PR DESCRIPTION
**Pull request by Spreeuw**
This PR stores the font metrics as JSON instead of PHP, keeping backwards compatibility with existing `.php` cache files and automatically migrating them to the JSON format.

**Background**
We use dompdf in a plugin for WordPress, and use the WordPress upload folder (`wp-content/uploads/`) for the (temporary) font files, for a lack of a better alternative. This works fine, except that there are security plugins for WordPress that don't like PHP files being written to that folder (and its subfolders), which need to be writable and thus could theoretically pose a security risk. When these files are removed in automated cleanup processes, the fonts are rendered incorrectly in dompdf.

Using JSON instead of a PHP file with `return array()` not only prevents this conflict, but also mitigates a potential attack vector that is similar to `eval()` in usage.

The provided solution is backwards compatible, following the same pattern that was used for the cache file changes introduced by dompdf 0.6 (which stored the data as plain text in a file `php_$name.ufm` and processed the contents using `eval()`).
To avoid having to introduce `eval()` into the code again, I have opted to leave the previous compatibility as-is. This means that if someone is migrating from 0.5 to 1.X, the cache files would first be converted to the `.ufm.php` format, and then to the new `.ufm.json` format in a second step. This would be a one-time conversion in an upgrade scenario that is not very likely.

### CODE REVIEW

**Comment by bsweeney** [comment]
Thanks for the pull request. This is a long-standing request, see #1543.

FYI, PRs should be based on the Develop branch.

**Comment by Spreeuw** [comment]
Thanks! This PR currently only addresses the font metrics files themselves, not the index ('dompdf_font_family_cache.php`). I'll see if I can add that too.

**Comment by Spreeuw** [comment]
The last commits also changed the index files (`dompdf_font_family_cache.php` and `dompdf_font_family_cache.dist.php`) to the JSON format.

Sharing some of the  design choices I have made:

Rather than storing an absolute path to the font files, in the current release, `FontMetrics` processes the data during the save process, replacing known paths from the `fontDir` and `rootDir` options by variable names (which used to be contants in dompdf 0.6):
https://github.com/dompdf/dompdf/blob/3ed5eab9a259c909679d781daab6b71d4de94e57/src/FontMetrics.php#L100-L101

Upon reading the files, these variables are then set so that the resulting array has the full paths again:
https://github.com/dompdf/dompdf/blob/3ed5eab9a259c909679d781daab6b71d4de94e57/src/FontMetrics.php#L125-L133

In this PR, I've changed this slightly, leaving out the direct reference and instead splitting the different locations into three categories: `rootDir` (for the bundled `.dist` fonts), `fontDir` (for user defined fonts inside the `fontDir` defined in options) and `absolute` (for fonts that reside in neither folders*). Now, instead of loading the families directly into the `$fontLookup` property as before (which needs full paths and would thus modify the data directly), I load them separately into their own properties `$distFonts` and `$userFonts`. This ensures that the data representation itself is not changed and can be saved back without any preprocessing (removing base paths).
After loading this data, it is processed into a separate property `$fontFamilies` that replaces the previous `$fontLookup`. This is a singular list with all the families from the 3 categories combined (user fonts preferred over dist fonts), with their full working paths.

The rest is pretty similar, although I needed to shuffle some variables in the `registerFont()` method to be able to maintain the separation between full paths (for saving the font data such as `.ttf` and `.ufm` into the right location). I didn't touch the structure itself, but think that some helper methods for getting a path for a family file with a specific extension would make this code more readable.

There is some wild code here that I didn't touch either, because honestly I couldn't grasp what this was doing:
https://github.com/dompdf/dompdf/blob/3ed5eab9a259c909679d781daab6b71d4de94e57/src/FontMetrics.php#L186-L197
It feels like that could (should?) be simpler...

Legacy `.php` cache files are converted into the new JSON format automatically and saved, but **not** deleted (this holds for both the indexes (`.php` and `.dist.php` as well as the metrics cache `.ufm.php`). This is suboptimal and I am certainly not opposed to unlinking the files (especially the index file because it would be processed on each run), but I'd like input on this. @bsweeney thoughts?

I've taken much care to make this as backwards compatible as possible, and being a non-breaking change I think this could be included in a 1.X update rather than 2.X (but I don't know your expected timeline for that release).

*One of the 'features' of the current implementation using PHP is that the user defined fonts index (`dompdf_font_family_cache.php`) can be edited directly to (theoretically) link to locations outside of the fonts folder defined in the dompdf Options. While perhaps not super likely, these will still function properly by being saved as absolute paths in the new JSON file.

**Comment by Spreeuw** [comment]
by the way, I didn't change the filename itself, but I think the name `dompdf_font_family_cache` is not very accurate. It is not cache but simply a list of font families. `font-families.json` and `font-families-bundled.json` may be more approriate?

**Comment by bsweeney** [comment]
>  I didn't change the filename itself, but I think the name `dompdf_font_family_cache` is not very accurate. It is not cache but simply a list of font families. `font-families.json` and `font-families-bundled.json` may be more approriate?

I agree that the name doesn't quite match the purpose. I don't have a good feel for what would be a better name. What you have would work.

**Comment by bsweeney** [comment]
> There is some wild code here that I didn't touch either, because honestly I couldn't grasp what this was doing:

That's just trying to make sure that the file name is simple enough not to cause problems for the local filesystem. That's in there mostly to protect from weirdly named remote files.

**Comment by makss** [comment]
@Spreeuw, Thanks for your PR, this solves issue #2161 too.

**Comment by bsweeney** [comment]
I'm ready to pull this in. If you have time to rebase and address conflicts that'd be great, but if not no worries.

**Comment by Spreeuw** [comment]
@bsweeney unfortunately I don't have time to resolve this at the moment

**Comment by bsweeney** [comment]
That's awesome I can take it from here.

**Pull request merged**
